local filesToDownload = {"startup.lua","gkos/logo.nfp","gkos/system/init.lua","gkos/system/apis/registry.lua","gkos/system/apps/pkg/main.lua"}
function download(filename)
	local req = http.get("https://raw.githubusercontent.com/Kozodoychik/GK-OS/1.0.0/os/"..filename)
	local file = fs.open("/"..filename,"w")
	file.write(req.readAll())
	file.close()
end
term.setBackgroundColor(1)
term.setTextColor(128)
term.clear()
term.setCursorPos(18,8)
term.write("GK-OS v1.0.0 Setup")
term.setCursorPos(15,10)
for key, value in ipairs(filesToDownload) do
	term.clearLine()
	term.setCursorPos(15,10)
	term.write(value)
	download(value)
end
term.clearLine()
term.setCursorPos(15,10)
term.write("Installing some packages...")
shell.setAlias("pkg","/gkos/system/apps/pkg/main.lua")
shell.run("pkg","install","recovery","/gkos/recovery","silent")
settings.set("gkstartup.isUnlocked",false)
settings.save("/.systemSettings")
fs.delete("/.temp")
term.clearLine()
term.setCursorPos(15,10)
term.write("Done! Press any key to reboot")
os.pullEvent("key")
os.reboot()
