os.loadAPI(_SYSPATH.."system/apis/registry.lua")
term.setBackgroundColor(colors.black)
term.setTextColor(colors.white)
term.clear()
term.setCursorPos(1,1)
shell.setAlias("pkg",_SYSPATH.."system/apps/pkg/main.lua")
if not fs.exists(_SYSPATH.."system/.registry") then
	fs.makeDir(_SYSPATH.."system/.registry")
	registry.createReg()
	registry.createKey("system","systemVersion","1.0.0")
	term.write("Username: ")
	local user = read()
	term.write("Password: ")
	local passw = read()
	registry.createKey("user","username",user)
	fs.makeDir(_SYSPATH.."user")
	fs.makeDir(_SYSPATH.."user/"..user)
	fs.makeDir(_SYSPATH.."user/"..user.."/apps")
	local passwFile = fs.open(_SYSPATH.."user/"..user.."/.passwrd","w")
	passwFile.write(passw)
	passwFile.close()
	shell.run("pkg","install","gui",_SYSPATH.."system/apps/gui")
end
shell.run(_SYSPATH.."system/apps/gui/main.lua")
