os.loadAPI("/gkos/system/apis/registry.lua")
term.setBackgroundColor(colors.black)
term.setTextColor(colors.white)
term.clear()
term.setCursorPos(1,1)
shell.setAlias("pkg","/gkos/system/apps/pkg/main.lua")
if not fs.exists("/gkos/system/.registry") then
	fs.makeDir("/gkos/system/.registry")
	registry.createReg()
	registry.createKey("system","systemVersion","1.0.0")
	term.write("Username: ")
	local user = read()
	term.write("Password: ")
	local passw = read()
	registry.createKey("user","username",user)
	fs.makeDir("/gkos/user")
	fs.makeDir("/gkos/user/"..user)
	fs.makeDir("/gkos/user/"..user.."/apps")
	local passwFile = fs.open("/gkos/user/"..user.."/.passwrd","w")
	passwFile.write(passw)
	passwFile.close()
	shell.run("pkg","install","gui","/gkos/system/apps/gui")
end
shell.run("/gkos/system/apps/gui/main.lua")
