os.loadAPI("apis/registry.lua")
local systemVersion = registry.readKey("system", "systemVersion")
local layout = gui.Layout:new()
layout:init()
layout:setBGColor(colors.white)
layout:newRect("headerRect", 1, 1, 51, 2, colors.lightBlue)
layout:newLabel("headerLabel", 20, 2, "About ZheOS", colors.white, colors.lightBlue)
layout:newLabel("versionLabel", 2, 5, "ZheOS version "..systemVersion, colors.black)
layout:mainLoop()