os.setWindowLabel("About ZheOS")
local systemVersion = registry.readKey("system", "systemVersion")
local layout = gui.Layout:new()
layout:init()
layout:setBGColor(colors.white)
layout:newRect("headerRect", 1, 1, 51, 2, colors.lightBlue)
layout:newLabel("headerLabel", 20, 2, "About ZheOS", colors.white, colors.lightBlue)
layout:newLabel("versionLabel", 2, 5, "ZheOS version "..systemVersion, colors.black)
layout:newLabel("idLabel", 2, 7, "Computer ID: "..os.getComputerID(), colors.black)
layout:newLabel("labelLabel", 2, 9, "Computer label: "..(os.getComputerLabel() or "(empty)"), colors.black)
layout:newLabel("driveFreeSpaceLabel", 2, 11, "Free space: "..fs.getFreeSpace("/").." bytes", colors.black)
layout:mainLoop()