os.loadAPI("/ospixel/system/apis/registry.lua")
term.setBackgroundColor(colors.black)
term.setTextColor(colors.white)
term.clear()
term.setCursorPos(1,1)
shell.setAlias("pkg","/ospixel/system/apps/pkg/main.lua")
if not fs.exists("/ospixel/system/.registry") then
	fs.makeDir("/ospixel/system/.registry")
	registry.createReg()
	registry.createKey("system","systemVersion","1.0.0")
	term.write("Username: ")
	local user = read()
	registry.createKey("user","username",user)
	shell.run("pkg","install","gui","/ospixel/system/apps/gui")
end
shell.run("/ospixel/system/apps/gui/main.lua")
